name: 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
#    container: 
#      image: condaforge/linux-anvil

    steps:
      # This step check out a copy of your repository
      - name: Check out repository code
        uses: actions/checkout@v2
      # Display OS release
      - name: Display os-release
        run: cat /etc/os-release
      # Setup miniconda
      - name: Setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          activate-environment: foo
      - name: Build tango-idl Conda package
        shell: bash -l {0}
        run: |
          conda info
          conda list
          ls -l $GITHUB_WORKSPACE
          conda install conda-build
          conda build $GITHUB_WORKSPACE/conda-recipes/tango-idl --output-folder=$GITHUB_WORKSPACE/dist-idl
          mkdir $GITHUB_WORKSPACE/artifacts
          cp $GITHUB_WORKSPACE/dist-idl/tangoidl*.bz2 $GITHUB_WORKSPACE/artifacts/
      - name: Upload Conda Package as artifact
        uses: actions/upload-artifact@v1
        with:
          name: tango-idl-conda-package
          path: dist-idl

