name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: 
      image: condaforge/linux-anvil

    steps:
      # This step check out a copy of your repository
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Hello world
        run: echo 'Hello world!!'
        id: hello
      # This step display the checked out README.md file
      - name: Display README
        run: cat $GITHUB_WORKSPACE/README.md
      - name: Display os-release
        run: cat /etc/os-release
